
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 04 13:37:18 CET 2015
//----------------------------------------------------

package rs.ac.bg.etf.pp1.sv110059;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LTE = 17;
  public static final int CONST = 24;
  public static final int STRCONST = 44;
  public static final int NOT_EQUAL = 22;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int MINUS = 21;
  public static final int RPAREN = 7;
  public static final int AND = 25;
  public static final int LT = 16;
  public static final int OR = 28;
  public static final int COMMA = 8;
  public static final int CLASS = 34;
  public static final int INC = 31;
  public static final int DIV = 19;
  public static final int PLUS = 11;
  public static final int IF = 36;
  public static final int IS_EQUAL = 23;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 39;
  public static final int MOD = 20;
  public static final int IDENT = 40;
  public static final int BREAK = 30;
  public static final int VOID = 13;
  public static final int GTE = 15;
  public static final int TIMES = 29;
  public static final int ELSE = 35;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 26;
  public static final int READ = 37;
  public static final int CHARCONST = 41;
  public static final int RSQUARE = 27;
  public static final int WHILE = 33;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 43;
  public static final int EXTENDS = 42;
  public static final int DEC = 32;
  public static final int GT = 14;
  public static final int PRINT = 9;
}

