
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 01 16:00:46 CET 2015
//----------------------------------------------------

package rs.ac.bg.etf.pp1.sv110059;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LTE = 18;
  public static final int CONST = 25;
  public static final int STRCONST = 38;
  public static final int NOT_EQUAL = 23;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int MINUS = 22;
  public static final int RPAREN = 7;
  public static final int AND = 26;
  public static final int LT = 17;
  public static final int OR = 29;
  public static final int COMMA = 8;
  public static final int CLASS = 35;
  public static final int INC = 32;
  public static final int DIV = 20;
  public static final int PLUS = 11;
  public static final int IF = 40;
  public static final int IS_EQUAL = 24;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 43;
  public static final int MOD = 21;
  public static final int IDENT = 44;
  public static final int BREAK = 31;
  public static final int VOID = 13;
  public static final int GTE = 16;
  public static final int TIMES = 30;
  public static final int ELSE = 39;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 27;
  public static final int READ = 41;
  public static final int CHARCONST = 36;
  public static final int RSQUARE = 28;
  public static final int WHILE = 34;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 37;
  public static final int EXTENDS = 14;
  public static final int DEC = 33;
  public static final int GT = 15;
  public static final int PRINT = 9;
}

